### ISSUE TITLE
Non-determinism in pods

### ISSUE THREAD

**Issue by globalcitizen** [appc/spec#381] opened 2015-05-06 16:25 UTC
Pod manifests (multi-component services) allow inspecific versioning ("version=latest") and input from the network (during the process termed 'reification' in the documents) and are therefore non-deterministic, which while conceptually simple at the outset actually creates numerous potential edge-cases and problems (this is the same approach docker has historically taken and is really a false economy, long term!)

**Comment by jonboulle** [comment] 2015-05-06 20:16
This flexibility is intentional to facilitate deployment templates. I am
not yet sure this is sufficiently concerning to prohibit such behaviour,
environments can remain entirely deterministic through use of image IDs. We
really need to explicate some examples of the template pattern and
suggested practices, /cc @vbatts

This is duped with another issue, will find when IFOK...
Am 06.05.2015 09:25 schrieb "Walter Stanish" <notifications@github.com>:

**Comment by jonboulle** [comment] 2015-05-08 05:12
Closing as dupe of #295 , let's chase up there

**Closed by jonboulle** 2015-05-08 05:12 UTC
