### ISSUE TITLE
spec: Clarify issues regarding UUIDs of pods

### ISSUE THREAD

**Issue by schancel** [appc/spec#324] opened 2015-04-27 20:53 UTC
The spec says:

> UUIDs assigned to pods MUST be unique for a given instance of a metadata service. Hence, 
> implementations of a metadata service shared among executors SHOULD either provide centralized
> allocation of UUIDs or partition the UUID space between individual executors.

Presumably this is because the spec calls out that:

> The executor must assign an RFC4122 UUID to each pod. This UUID is exposed to the pod through 
> the Metadata Service.

However, I didn't see any other place aside from the metadata service that the UUID is exposed.   Why not remove that the executor must generate the UUID, and then you can just say:

> UUIDs assigned to pods MUST be unique for a given instance of a metadata service.

The implementation can then have the metadata service itself generate the UUID if desired.

If I am missing a technical reason to have this generated in the executor -- maybe call it out in the spec?

**Comment by jonboulle** [comment] 2015-04-27 22:56
@schancel this is a dupe of #103 but your ticket is phrased better :-). want to submit a patch for this?

**Comment by schancel** [comment] 2015-04-28 01:06
Sure, I can do that.  I don't think that there need be any associated code changes for this -- it's just removing a few lines.  Just say something on the PR if I missed something that is needed in the binaries.

**Comment by jonboulle** [comment] 2015-04-28 02:15
No, I'm pretty sure you're right and it's just a wording change. Thanks!
Am 27.04.2015 18:06 schrieb "Shammah Chancellor" <notifications@github.com>:

**Closed** 2015-04-29 22:08 UTC
