### ISSUE TITLE
ace validators leave db files in /tmp

### ISSUE THREAD

**Issue by NeilW** [appc/spec#507] opened 2015-09-29 08:43 UTC
If you run the ace validator twice it will fail on the second attempt. There doesn't seem to be anything in the validator that cleans up the db files.

core@srv-qx9es ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=815.0.0
VERSION_ID=815.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 815.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

core@srv-qx9es ~ $ sudo rkt --insecure-skip-verify run --private-net --volume=database,kind=host,source=/tmp http://orbit.brightbox.com/v1/acc-tqs4c/downloads/ace%2Dvalidator%2Dmain.aci http://orbit.brightbox.com/v1/acc-tqs4c/downloads/ace%2Dvalidator%2Dsidekick.aci 
2015/09/29 08:42:30 Preparing stage1
2015/09/29 08:42:30 Loading image sha512-a4451ee4dffb0292256a41ec9d196037e23ec0d08e92923989c9237a12bddc68
2015/09/29 08:42:30 Loading image sha512-6eae0e9311f5c9724302964ead70b74e7972d21c36f148c239783e0f9b1b879e
2015/09/29 08:42:30 Writing pod manifest
2015/09/29 08:42:30 Setting up stage1
2015/09/29 08:42:30 Writing image manifest
2015/09/29 08:42:30 Wrote filesystem to /var/lib/rkt/pods/run/44b102e7-87a1-4f3e-9f99-bc54d2edc662
2015/09/29 08:42:30 Writing image manifest
2015/09/29 08:42:30 Writing image manifest
2015/09/29 08:42:30 Pivoting to filesystem /var/lib/rkt/pods/run/44b102e7-87a1-4f3e-9f99-bc54d2edc662
2015/09/29 08:42:30 Execing /init
[309214.157276] ace-validator[5]: prestart OK
[309214.212231] ace-validator[14]: main OK
[309214.212731] ace-validator[6]: sidekick OK
[309214.221690] ace-validator[19]: poststop OK

core@srv-qx9es ~ $ sudo rkt --insecure-skip-verify run --private-net --volume=database,kind=host,source=/tmp http://orbit.brightbox.com/v1/acc-tqs4c/downloads/ace%2Dvalidator%2Dmain.aci http://orbit.brightbox.com/v1/acc-tqs4c/downloads/ace%2Dvalidator%2Dsidekick.aci 
2015/09/29 08:39:56 Preparing stage1
2015/09/29 08:39:56 Loading image sha512-a4451ee4dffb0292256a41ec9d196037e23ec0d08e92923989c9237a12bddc68
2015/09/29 08:39:56 Loading image sha512-6eae0e9311f5c9724302964ead70b74e7972d21c36f148c239783e0f9b1b879e
2015/09/29 08:39:56 Writing pod manifest
2015/09/29 08:39:56 Setting up stage1
2015/09/29 08:39:56 Writing image manifest
2015/09/29 08:39:56 Wrote filesystem to /var/lib/rkt/pods/run/b9c112d5-f360-4ec6-9b57-7886b97c2f14
2015/09/29 08:39:56 Writing image manifest
2015/09/29 08:39:56 Writing image manifest
2015/09/29 08:39:56 Pivoting to filesystem /var/lib/rkt/pods/run/b9c112d5-f360-4ec6-9b57-7886b97c2f14
2015/09/29 08:39:56 Execing /init
[309060.374565] ace-validator[6]: sidekick FAIL
[309060.375124] ace-validator[6]: ==> file "/db/sidekick" exists unexpectedly
[309060.380968] ace-validator[5]: prestart OK
[309060.423788] ace-validator[14]: main FAIL
[309060.424195] ace-validator[14]: ==> file "/db/main" exists unexpectedly
[309060.434405] ace-validator[23]: poststop OK
Warning! D-Bus connection terminated.
Failed to start reaper.service: Connection reset by peer

**Comment by jonboulle** [comment] 2015-09-29 16:30
Closing this as a dupe of #113. This should be a pretty easy fix so help would be most welcome.

**Closed by jonboulle** 2015-09-29 16:30 UTC
